### ISSUE TITLE
 Provisioning task start executing after the first approved.

### ISSUE THREAD

**Issue by ghost** [pemcg/multi-level-approval#2]
Hi, I have been test this multi approval to the days. When I just order the service. The first approver can get an email. Then I approved that, and the provisioning task started executing. The VM was be created. The second multi level didn't work for me.

**Comment by pemcg** [comment]
Hi, I'm afraid the code is just an example of what can be done, it was written as a PoC and abandoned because it's pretty ugly. The email methods have subsequently changed so if you still want to try to use this you may need to check and modify the new email methods accordingly. Also check that the hidden 'approval_level' dialog is being passed through with the value of 'multi'. 

Cheers,
pemcg
